---
name: On Push - Build and code check

"on":
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-tester:
    uses: ./.github/workflows/template-build-and-push.yml
    with:
      image_name_base: colk-tech/manaba-collector
      image_name_suffix: -tester
      build_target: tester

  devcontainer:
    name: Dev Container
    uses: ./.github/workflows/template-devcontainer-ci.yml
    permissions:
      contents: read

  python-ci:
    needs: build-tester
    uses: ./.github/workflows/template-python-ci.yml
    with:
      image: ${{ needs.build-tester.outputs.tags }}
