---
name: On Push - Build and Code Check

"on":
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  docker-ci:
    uses: ./.github/workflows/template-docker-ci.yml
    permissions:
      contents: read
      id-token: write

  devcontainer-ci:
    uses: ./.github/workflows/template-devcontainer-ci.yml
    permissions:
      contents: read
